### PR TITLE
Updates etools-profile-dialog to 2.0.9

### PR DESCRIPTION
**Pull request by drzackyll**
[ch11651]

### CODE REVIEW

**Comment by acory** [comment]
Change already done in another PR

**Comment by drzackyll** [comment]
@acory are you sure this is already done? this is a new release of etools-profile-dialog in polymer 1 that adds the user's name to the dialog. i don't see this in any open PRs

**Comment by acory** [comment]
@drzackyll In this PR: https://github.com/unicef/etools-auditor-portal/pull/61/files which was merged in develop

**Comment by drzackyll** [comment]
@acory ah i see. going to the auditor portal page on github seems to default to the master branch. i didn't see it in bower.json there and assumed it was develop.

**Pull request closed without merging**
