### PR TITLE
fix npm install

### PR DESCRIPTION
**Pull request by czue**
this fixes https://github.com/unicef/etools-issues/issues/786

I think maybe has to do with some of the submodule changes I made to `etools-infra` affecting where the `.git` folder ends up, but this change should (I think) be future proof.

@vkurup @robertavram

### CODE REVIEW

**Comment by czue** [comment]
the resulting installed commit hook is sloooooow.... :snail:

**Comment by robertavram** [comment]
@roman-karpovich is the hook needed?
can we eliminate the hook altogether?

**Comment by roman-karpovich** [comment]
@robertavram cure, this hook can be removed entirely. No need to run tests every time, CI should do this.

**Comment by robertavram** [comment]
@roman-karpovich awesome!
thanks

**Pull request merged**
